 2023-10-02 15:16:28.772204 : Error :  HTTPConnectionPool(host='192.168.4.70', port=8020): Max retries exceeded with url: /api/vehicle/getprevtransaction (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001D8404A6610>, 'Connection to 192.168.4.70 timed out. (connect timeout=None)'))    
----------------------------------------------------------------------
 2023-10-02 15:16:48.987616 : Error :  HTTPConnectionPool(host='192.168.4.70', port=8020): Max retries exceeded with url: /api/vehicle/getprevtransaction (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000018E2E119F50>, 'Connection to 192.168.4.70 timed out. (connect timeout=None)'))    
----------------------------------------------------------------------
